### ISSUE TITLE
 پادکسب جدید بخش موسیقی

### ISSUE THREAD

**Issue by snip77** [Ashkan-rmk/awesome-persian-podcasts#21]
پادکست آدینه رو هم گوش کنید برای موسیقی هستش.

**Comment by Ashkan-rmk** [comment]
اگر لینکی هم ازش دارین بدین ممنون

**Comment by snip77** [comment]
حدود 73 قسمته
میتونی توی تلگذام از ربات melobot همه لینک هاشو برداری

**Comment by Ashkan-rmk** [comment]
@snip77 یعنی وبسایتی یا کانال تلگرام ندارن که سرجمع باشه تمامشون یکجا؟ اینجا باید ما فقط یک لینک از منبع بزاریم .

**Comment by snip77** [comment]
توی این بات سرچ  کنید:
@melobot
سرچ کنید adine
شاهین طاها هم درست میکنه.
هر هفته جمعه ها منتشر میشه

**Comment by SamaneYaghoobi** [comment]
@snip77 میکس موزیک هستش درسته؟

**Comment by snip77** [comment]
پادکسته
هر هفته موزیکای اون هفته رو از هر کدپم یه تیکشو میزاره حدود 30 دقیقه هستش هر کدوم
