### ISSUE TITLE
تغیر در چینش جداول و پیوندهایشان

### ISSUE THREAD

**Issue by mehrad77** [Ashkan-rmk/awesome-persian-podcasts#4]
اول از همه ایول به خاطر این کار خوب :)
دوم آن‌که بهتر نیست به جای این‌که به پادکست‌ها به کانال تلگرامشون پیوند بخورن، به سایتشون پیوند بشن؟ در کنارش لینک تلگرامشون هم باشه مثلا
اگر موافق بودید که پول‌ریکوئست بدم یا ..

**Comment by SamaneYaghoobi** [comment]
@mehrad77 
مرسی ازت :)
عاره این عالیه! ما تا اینجا تمام سعی مون این بوده که لینک کانال تلگرام نذاریم 
ولی بعضی پادکست‌ها فقط توی تلگرام بودن یا اینکه لینکی دیگه ازشون پیدانکردیم
 اگر پادکستی هست که آدرس دیگه ای غیر از کانال تلگرامشو داری حتمن پول‌ریکوئست بده
ممنونم :)
